### ISSUE TITLE
Display Travis Build Status Image at top of README

### ISSUE THREAD

**Issue by mccrodp** [MarketoMA/marketo_ma#11]
I had this issue on Marketo REST also https://github.com/mccrodp/marketo_rest/issues/1, I'd be interested in getting this running, it would be good to see a green light before starting on PRs.

**Comment by jyokum** [comment]
7.x-2.x and 8.x-2.x branches are all running properly on Travis.

https://travis-ci.org/MarketoMA/marketo_ma/branches

**Comment by mccrodp** [comment]
Awesome. Let's display build status at the top of the repo then: https://docs.travis-ci.com/user/status-images/

(I was looking at the failing PR and presumed all were failing)

**Comment by mccrodp** [comment]
I rethought this and as the same README gets synced with Drupal.org, perhaps it's not ideal ideal and the image/link won't be active. Would be nice on Drupal.org project page alternatively, but not sure how possible that is.
