### ISSUE TITLE
What is REST synchronous v.s. asynchronous?

### ISSUE THREAD

**Issue by mccrodp** [MarketoMA/marketo_ma#12]
I've seen this in the UI and was wondering if it is anything more than a remnant from 1.x / SOAP implementation? Otherwise what is the difference and how is it used? i.e. - in synchronous do we block further calls until a response is received somehow?

**Comment by jyokum** [comment]
Synchronous will send lead updates to Marketo immediately as part of a page request. Async will queue the updates and send to Marketo whenever Drupal cron runs.

**Comment by mccrodp** [comment]
Ahh yes, I remember seeing that now that you mention it. Great, thanks. Maybe that's something I should address in the README: https://github.com/MarketoMA/marketo_ma/issues/13
